---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-samba
  tasks:
    - name: Verify the 'restart smb' handler.
      command: echo
      notify: restart smb
      changed_when: false
