---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: instance-stretch
    image: debian:9
  - name: instance-buster
    image: debian:10
provisioner:
  name: ansible
verifier:
  name: testinfra
