---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 3 * * 4"

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.6'

      - name: Install pipenv.
        run: pip3 install pipenv

      - name: Install test dependencies.
        run: python3 -m pipenv sync

      - name: Run Molecule tests.
        run: python3 -m pipenv run molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
